# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "DUA Scent AI raheali"
client_id = "a98e2f95f121f364264776ded9e7fd63"
application_url = "https://dua-scent-harden-raheali.onrender.com/"
embedded = true
extension_directories = [ "extensions/*" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_publications,unauthenticated_read_product_listings,write_app_proxy,write_inventory,write_products,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [
  "https://dua-scent-harden-raheali.onrender.com/api/shopify/auth/callback"
]
