"""Structured, production-friendly logging. Every line is one JSON object: timestamp, level,
logger name, message, and a request_id when the log happened inside a request (set by
RequestContextMiddleware below). Never log OpenAI/DB/Odoo credentials or full auth headers --
every call site in this codebase that logs a request already hand-picks safe fields rather than
dumping headers/payloads wholesale (see odoo_inventory.py's own comment on this).
"""

import json
import logging
import time
import traceback
import uuid
from contextvars import ContextVar

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request

_request_id_var: ContextVar[str | None] = ContextVar("request_id", default=None)


class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload = {
            "timestamp": self.formatTime(record, "%Y-%m-%dT%H:%M:%S%z"),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        request_id = _request_id_var.get()
        if request_id:
            payload["request_id"] = request_id
        if record.exc_info:
            payload["exc_info"] = safe_exception_summary(record.exc_info[1])
        return json.dumps(payload)


_MAX_FRAMES = 12


def safe_exception_summary(error: BaseException | None) -> dict:
    """Phase 6: what failed and where, WITHOUT exception messages. Messages routinely embed
    payloads: validation errors quote their input, database errors quote statements and values,
    HTTP errors quote URLs. Types, the cause chain and code locations are enough to diagnose."""
    chain: list[str] = []
    seen: set[int] = set()
    current = error
    while current is not None and id(current) not in seen and len(chain) < 6:
        seen.add(id(current))
        chain.append(type(current).__name__)
        current = current.__cause__ or current.__context__
    frames = []
    for frame in traceback.extract_tb(error.__traceback__)[-_MAX_FRAMES:] if error is not None else []:
        frames.append(f"{frame.filename.rsplit('/app/', 1)[-1] if '/app/' in frame.filename else frame.filename.rsplit('/', 1)[-1]}:{frame.lineno}:{frame.name}")
    return {"types": chain, "frames": frames}


def configure_logging(level: str) -> None:
    handler = logging.StreamHandler()
    handler.setFormatter(JsonFormatter())
    root = logging.getLogger()
    root.handlers = [handler]
    root.setLevel(level.upper())
    # Phase 6: the HTTP client libraries log every outbound request URL at INFO. The inventory
    # lookup puts private item codes in its query string, so those lines are a data leak, not
    # diagnostics. Outbound calls are already logged by the application with safe fields.
    for noisy in ("httpx", "httpcore"):
        logging.getLogger(noisy).setLevel(logging.WARNING)


class RequestContextMiddleware(BaseHTTPMiddleware):
    """Assigns a request_id (visible on every log line emitted while handling this request) and
    logs one summary line per request: method, path, status, duration_ms.
    """

    async def dispatch(self, request: Request, call_next):
        request_id = str(uuid.uuid4())
        token = _request_id_var.set(request_id)
        started_at = time.monotonic()
        try:
            response = await call_next(request)
        finally:
            _request_id_var.reset(token)
        duration_ms = round((time.monotonic() - started_at) * 1000, 1)
        # Phase 6: the matched ROUTE TEMPLATE, never the raw path or query string (both can carry
        # identifiers or arbitrary client text). The request id is generated by this server.
        route = request.scope.get("route")
        template = getattr(route, "path", None) or "unmatched"
        logging.getLogger("app.request").info(
            "%s %s -> %s (%sms) [%s]",
            request.method, template, response.status_code, duration_ms, request_id,
        )
        response.headers["X-Request-Id"] = request_id
        return response
